local_backend:
  url: http://localhost:8082/api/v1
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# These lines should *not* be indented
media_folder: "/src/assets"
public_folder: "assets"

locale: 'pl'
i18n:
  structure: single_file
  locales: [ pl ]
  default_locale: pl

collections:
  - name: 'settings'
    label: 'Ustawienia'
    sortable_fields: [ ]
    i18n:
      structure: single_file
      locales: [ pl ]
    files:
      - file: src/content/settings/meta.md
        label: 'Meta tagi'
        name: 'meta'
        i18n: true
        create: false
        delete: false
        editor:
          preview: false
        fields:
          - label: "Meta Tagi"
            hint: 'Meta tagi - https://pomoc.home.pl/baza-wiedzy/najwazniejsze-znaczniki-meta-i-ich-funkcje-meta-tagi'
            i18n: true
            name: "metaTags"
            widget: "object"
            fields:
              - { label: "Tytuł strony", name: "title", hint: 'Widoczny w tytule przeglądarki', widget: "string" , i18n: true }
              - { label: "Meta description - opis strony", name: "description", hint: 'Najlepiej między 50 a 150 znaków', widget: "text", i18n: true }
              - { label: "Meta keywords - Słowa kluczowe", name: "keywords", hint: 'Oddzielone przecinkami', widget: "text", i18n: true }
          - label: "Tagi Open Graph"
            hint: "Tagi Open Grap - Np. Jak ma wyglądać podgląd, kiedy wysyłasz stronę przez Facebooka https://lumo.pl/blog/open-graph/. Sprawdź jak wygląda podgląd na https://developers.facebook.com/tools/debug/"
            i18n: true
            name: "openGraph"
            widget: "object"
            summary: 'Tagi Open Graph'
            fields:
              - { label: "Tytuł - Podgląd w social mediach", name: "title", widget: "string", hint: 'Tytuł podglądu kiedy np. kiedy wysyłasz stronę przez Facebooka albo LinkedIn', i18n: true }
              - { label: "Opis - Podgląd w social mediach", name: "description", widget: "text", i18n: true }
              - label: "Zdjęcie - Podgląd w social mediach"
                name: "image"
                widget: "image"
                choose_url: false
                public_folder: "/src/assets/"
                i18n: "duplicate"
  - label: "Tydzień"
    name: "week"
    folder: "src/content/weeks"
    slug: "{{fields.dateFrom}}"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Tytuł", name: "title",   widget: "string" , i18n: true }
      - { label: "Tydzień od - ", name: "dateFrom", widget: "datetime", format: "YYYY-MM-DD",  i18n: true,  }
      - { label: "Tydzień do - ", name: "dateTo", widget: "datetime", format: "YYYY-MM-DD",  i18n: true,  }
      - label: "Wydarzenia"
        name: "events"
        widget: "list"
        summary: '{{fields.title}}'
        fields:
          - { label: "Tytuł", name: "title", widget: "string" }
          - { label: "Data", name: "date", widget: "string" }
          - { label: "Miejsce", name: "location", widget: "string" }
          - { label: "Cena", name: "price", widget: "string", required: false }
          - { label: "Link do zapisów", name: "registration", widget: "string", required: false }
          - { label: "Link do wydarzenia", name: "link", widget: "string", required: false }
          - { label: "Opis", name: "body", widget: "markdown" }

